### ISSUE TITLE
Consider adding basic CORS support directly into the framework.

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#1194]
When dealing with APIs, supporting CORS is a common use case. It may make sense to include basic CORS functionality that allows access from any origin to the entire API.

Such a feature might be implemented along the lines of the following middleware component (albeit integrated directly into ``falcon.API``):

```py
# NOTE: Not fully tested

class CORSComponent(object):
    def process_response(self, req, resp, resource, req_succeeded):
        resp.set_header('Access-Control-Allow-Origin', '*')

        if (req_succeeded
            and req.method == 'OPTIONS'
            and req.get_header('Access-Control-Request-Method')
        ):
            # NOTE(kgriffs): This is a CORS preflight request. Patch the
            #   response accordingly.

            allow = resp.get_header('Allow')
            resp.delete_header('Allow')

            allow_headers = req.get_header(
                'Access-Control-Request-Headers', 
                default='*'
            )

            resp.set_headers((
                ('Access-Control-Allow-Methods', allow),
                ('Access-Control-Allow-Headers', allow_headers),
                ('Access-Control-Max-Age', '86400'),  # 24 hours
            ))
```

**Comment by santeyio** [comment]
I'll give this a shot

**Comment by foresmac** [comment]
I don't think this method makes sense; you'd have to already have an `on_options` method that generates a non-405 response. I think we might have used a mixin or middleware for this on a project; let me see if I can dig up the code.

**Comment by foresmac** [comment]
Ok, yeah, we used a mixin like the following:
```python
class PreflightOptions(object):

    def on_options(self, req, res, *args, **kwargs):
        res.status = falcon.HTTP_OK
```

But the CORS middleware worked on `process_resource`, so it got routed to a valid view.

Then we check the origin domain against a white list (`ALLOWED_ORIGINS`) and/or a regex (`ALLOWED_ORIGINS_REGEX`) defined elsewhere (we use a standard `app/config.py` file).

```python
def is_allowed_origin(origin):
    url = urlparse(origin)
    if url.netloc.split(':')[0] in ALLOWED_ORIGINS:
        return True
    else:
        for pattern in ALLOWED_ORIGINS_REGEX:
            if re.match(pattern, origin):
                return True
    return False
```

**Comment by kgriffs** [comment]
See also: https://github.com/falconry/falcon/issues/1220

**Comment by Mumrau** [comment]
Will this still be added in falcon 2.0?

**Comment by vytas7** [comment]
@Mumrau yes, that is the plan. Which could happen even quicker if someone wants to lend a hand and contribute :slightly_smiling_face:

**Comment by Mumrau** [comment]
I can't right now but I might give it a shot if nobody's doing it before
few weeks.

**Comment by silver8ack** [comment]
Is it just me, or does this not work with 1.4.1?

`
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    middleware=[CORSComponent,]
  File "REDACTED/venv/lib/python3.6/site-packages/falcon/api.py", line 156, in __init__
    middleware, independent_middleware=independent_middleware)
  File "REDACTED/venv/lib/python3.6/site-packages/falcon/api_helpers.py", line 78, in prepare_middleware
    'process_response')
  File "REDACTED/venv/lib/python3.6/site-packages/falcon/util/misc.py", line 245, in get_bound_method
    if six.get_method_self(method) is None:
AttributeError: 'function' object has no attribute '__self__'
`
