### ISSUE TITLE
Consider vendoring python-mimeparse

### ISSUE THREAD

**Issue by vytas7** [falconry/falcon#1420]
As brought up on https://github.com/falconry/falcon/pull/1383 and discussions on Gitter, we may consider vendoring ``python-mimeparse`` dependency.

Normally, vendoring Python dependencies is just an unnecessary burden:
* Laborious process to keep integrating upstream fixes
* *Pip* is good at handling dependencies
* Redundant duplication of libraries if the application is also using them

However, in this particular case of ``python-mimeparse`` it might be a compelling choice:
* As we are no longer relying on ``six``, this would make Falcon completely dependency-free, which, while not being much of a benefit in the *virtualenv* + *Pip* workflow, might ease distributing Falcon in other ways, such as packaging for Linux distributions (see for instance: https://github.com/dbtsai/python-mimeparse/issues/20 :arrow_left: note by @kgriffs )
* ``python-mimeparse`` is a mature package with a concise codebase (cone 190-line file), the pace of recent developments is rather moderate (at the time of writing, Jan 2019, the latest stable release on PyPi is from 2016)
* We would cythonize it together with the rest of Falcon, see also https://github.com/falconry/falcon/issues/1183

If we decide to do it, we need to keep an eye on upstream developments. We could introduce a Tox or Travis check that we have not fallen behind its stable PyPi version.

**Comment by Apteryks** [comment]
I'd rather have the option to use the regular mimeparse dependency, for packaging purposes (GNU Guix).  As it stands, we unbundled it already but it recently started failing like so:

```

    def test_deps_mimeparse_correct_package():
        """Ensure we are dealing with python-mimeparse, not mimeparse."""
    
>       tokens = mimeparse.mimeparse.__version__.split('.')
E       AttributeError: module 'mimeparse' has no attribute 'mimeparse'

tests/test_deps.py:11: AttributeError
```
Probably because of changes in mimeparse upstream.

**Comment by vytas7** [comment]
Hi @Apteryks!
We're sorry this has caused you problems.

FWIW, [`python-mimeparse`](https://pypi.org/project/python-mimeparse/) hasn't seen any release in a long while, so I doubt any upstream changes could be an issue _per se_. We have now taken over control of `python-mimeparse` and moved its maintenance under the Falconry umbrella, so we'll try to refine a way forward, potentially including an option to unbundle.

And I can indeed reproduce the issue, probably we haven't really payed attention to the possibility of unbundling (although I know Fedora Linux (and possibly Debian too) does unbundle, but I haven't looked how exactly they do that). NB that you will need a patch to replace the vendored imports with the global ones in either case.

I'll file an issue so that make a decision going forward.

**Comment by Apteryks** [comment]
Hello @vytas7 and thank you for the prompt reply.  You are correct that mimeparse hasn't changed upstream in recent years, it seems.  The problem would have rather been introduced with https://github.com/falconry/falcon/commit/f19039aaa1b435a174d4f041fb0728238c79d254; which access the __version__ variable through the `mimeparse.mimeparse` namespace rather than just `mimeparse`.  Reverting to the previous `mimeparse.__version__` works for me (we patch the top level import to read as just `import mimeparse` and provide the extra unbundled dependency).
